<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" total="24" passed="18">
  <reporter-output>
    <line>
      <![CDATA[ddddd]]>
    </line>
    <line>
      <![CDATA[ddddd]]>
    </line>
    <line>
      <![CDATA[ddddd]]>
    </line>
  </reporter-output>
  <suite name="测试列表" duration-ms="286" started-at="2018-12-12T09:34:12Z" finished-at="2018-12-12T09:34:12Z">
    <groups>
    </groups>
    <test name="恒丰银行系统启动状态监测测试" duration-ms="286" started-at="2018-12-12T09:34:12Z" finished-at="2018-12-12T09:34:12Z">
      <class name="com.test.test">
        <test-method status="PASS" signature="test01(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test01" duration-ms="32" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据1]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ddddd]]>
            </line>
          </reporter-output>
        </test-method> <!-- test01 -->
        <test-method status="PASS" signature="test01(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test01" duration-ms="1" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据2]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ddddd]]>
            </line>
          </reporter-output>
        </test-method> <!-- test01 -->
        <test-method status="PASS" signature="test01(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test01" duration-ms="3" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[shuju3]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[ddddd]]>
            </line>
          </reporter-output>
        </test-method> <!-- test01 -->
        <test-method status="PASS" signature="test02(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test02" duration-ms="9" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test02 -->
        <test-method status="PASS" signature="test02(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test02" duration-ms="4" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test02 -->
        <test-method status="PASS" signature="test02(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test02" duration-ms="6" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[shuju3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test02 -->
        <test-method status="PASS" signature="test03(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test03" duration-ms="3" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test03 -->
        <test-method status="PASS" signature="test03(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test03" duration-ms="2" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test03 -->
        <test-method status="PASS" signature="test03(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test03" duration-ms="2" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[shuju3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test03 -->
        <test-method status="FAIL" signature="test04(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test04" duration-ms="3" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.test.test04(test.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test04 -->
        <test-method status="FAIL" signature="test04(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test04" duration-ms="2" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.test.test04(test.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test04 -->
        <test-method status="FAIL" signature="test04(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test04" duration-ms="2" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[shuju3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.test.test04(test.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test04 -->
        <test-method status="PASS" signature="test05(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test05" duration-ms="3" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test05 -->
        <test-method status="PASS" signature="test05(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test05" duration-ms="2" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test05 -->
        <test-method status="PASS" signature="test05(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test05" duration-ms="3" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[shuju3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test05 -->
        <test-method status="FAIL" signature="test06(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test06" duration-ms="7" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据1]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.test.test06(test.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test06 -->
        <test-method status="FAIL" signature="test06(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test06" duration-ms="2" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.test.test06(test.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test06 -->
        <test-method status="FAIL" signature="test06(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test06" duration-ms="3" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[shuju3]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.test.test06(test.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test06 -->
        <test-method status="PASS" signature="test07(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test07" duration-ms="4" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test07 -->
        <test-method status="PASS" signature="test07(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test07" duration-ms="3" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test07 -->
        <test-method status="PASS" signature="test07(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test07" duration-ms="1" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[shuju3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test07 -->
        <test-method status="PASS" signature="test08(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test08" duration-ms="2" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据1]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test08 -->
        <test-method status="PASS" signature="test08(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test08" duration-ms="7" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[数据2]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test08 -->
        <test-method status="PASS" signature="test08(java.lang.String)[pri:0, instance:com.test.test@1a407d53]" name="test08" duration-ms="1" started-at="2018-12-12T17:34:12Z" data-provider="renmai" finished-at="2018-12-12T17:34:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[shuju3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test08 -->
      </class> <!-- com.test.test -->
    </test> <!-- 恒丰银行系统启动状态监测测试 -->
  </suite> <!-- 测试列表 -->
</testng-results>
